name = "ttnn-eltwise-performance"
compatibility_date = "2025-07-17"

[assets]
directory = "./dist"

# Custom domain configuration
[[routes]]
pattern = "ttnn-eltwise-performance.aswincloud.com/*"
zone_name = "aswincloud.com" 